spring.application.name=helpdesk-platform

# Postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk
spring.datasource.username=helpdesk_user
spring.datasource.password=helpdesk_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
